### ISSUE TITLE
Remove can panic under heavy deletion

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/go-merkle#9]
After long bug-hunting with the benchmarks, I discovered there is a bug in `IAVLTree.Remove()`, at least on the develop branch. If called enough with existing keys, and `Save()` called in between, it can leave to a SanityPanic.

There is only one Tree, no old `Copy()`s.  And only handled sequentially in a loop.

A trivial case doesn't seem to fail, so I am not sure where there error is...

**Comment by ebuchman** [comment]
You have code to reproduce?

**Comment by ebuchman** [comment]
Oh I see: https://github.com/tendermint/go-merkle/pull/10

**Comment by akalyaev** [comment]
@ebuchman see #10 (in particular: https://github.com/tendermint/go-merkle/pull/10/commits/3203bc089b9e5e3710550b700c76e4b0f1d52811)

**Comment by ethanfrey** [comment]
Okay, I am playing around today with isolating the commit, mainly jumping around the history and using `git cherry-pick 3203bc0`

Report:

develop (8bbe696) - `go test .` passes.  panics after cherry-pick

master (05042c6) - `go test .` passes. cherry-picked test also passes

tree-saver (3624668) - `go test .` complains about missing go-autofile dependency.  
  upon installing github.com/tendermint/go-autofile I discover that neither the master not develop branch compiles

In fact, every commit between develop and master has the same error about `go-autofile`, not even running :(

**Comment by ethanfrey** [comment]
Okay... so... all commits between 05042c6..8bbe696 import `go-autofile`, which seems to be a short-lived branch that redefines AutoFile from `go-common`. When I checkout the `develop` branch of `go-common`, I can get these tests to run.

Sorry if I come off a bit pushy, but the organization of the tendermint repo seems to work welll when there are one or two people working, focused on only one area at a time.  With more developers, these dependency management becomes more of a headache (I have had this in every job).  In order to make it easier for multiple people to collaborate on the repos, maybe we can start making a list of coding guidelines.  Here are my first two suggestions:

1. Make all dependencies explicit, especially when you depend on the develop branch of numerous other repos, maybe using glide (or another suggestion)

2. `import . "github.com/tendermint/go-common"` is an anti-pattern, please avoid.  Just making it `import cmn "github.com/tendermint/go-common"` requires like 4 more characters when using the functions, but makes the code much more clear and avoids naming conflicts like in go-autofile.

This is not the first time these two issues have bit me. And not just in tendermint.

**Comment by ethanfrey** [comment]
Bisect results (after fixing `go-autofile` issue)

```
* 8bbe696 (upstream/develop, origin/develop, develop) Remove WAL; Use Batching
* 6d0a664 Merge https://github.com/tendermint/go-merkle/pull/1
*   bfc4afe Merge pull request #3 from tendermint/tree_saver
|\
| * 3624668 (upstream/tree_saver) Use new Group semantics
| * 057319c First integration w/ WAL.  Need to test and prune old files
| * a84efae (HEAD) RemoveNode() & track orphans
| * f5f1b05 Initial commit of WAL
| * 2f295d8 Add WAL
|/
* 05042c6 (upstream/master, upstream/HEAD) use less append
```

2f295d8: `go test .` fails  - compile error
f5f1b05: `go test .` fails  - compile error
a84efae: `go test .` fails  - compile error
057319c: `go test .` fails  - compile error

3624668: `go test .` passes.  after applying the test, add adjusting it to the wal syntax, it also crashes

I wonder if the changes on develop are that important, and maybe better to go back to master? I also wonder about the whole persistence design. Well, at least the release go-merkle code is bug-free 😄

**Comment by jaekwon** [comment]
This should be fixed now in develop.
https://github.com/tendermint/go-merkle/commit/a74ffd5ba75ae1b453b5b1027489f92266a54958

Inner nodes were being modified, violating immutability.  Well, in "with-DB" mode the nodes aren't exactly immutable (we prune children on each .Save()), but at least the node's hash is invariant, and we maintain the .persisted flag as necessary.  The bug here is that we completely modify the contents of the inner node (which we shouldn't do) AND we do so without clearing the hash or the .persisted flag.  I believe I introduced this by accident when experimenting w/ optimizations.

**Comment by ethanfrey** [comment]
Looks good to me.  I closed the pull request, since you already merged the fix into develop.
